//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GorillaAdventuresEntities : DbContext
    {
        public GorillaAdventuresEntities()
            : base("name=GorillaAdventuresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUADRACICLO> CUADRACICLO { get; set; }
        public virtual DbSet<DETALLE_CUADRACICLO> DETALLE_CUADRACICLO { get; set; }
        public virtual DbSet<DETALLE_SERVICIO> DETALLE_SERVICIO { get; set; }
        public virtual DbSet<EXTRA> EXTRA { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TARJETA> TARJETA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
