//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ReservaMetadata))]
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.DETALLE_CUADRACICLO = new HashSet<DETALLE_CUADRACICLO>();
            this.DETALLE_SERVICIO = new HashSet<DETALLE_SERVICIO>();
        }
    
        public int ID_RESERVA { get; set; }
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_TARJETA { get; set; }
        public string NUM_TARJETA { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> IMPUESTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_RESERVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CUADRACICLO> DETALLE_CUADRACICLO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_SERVICIO> DETALLE_SERVICIO { get; set; }
        public virtual TARJETA TARJETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
